name: mor_chhattisgarh
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc:
  flutter_bloc:
  equatable:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - img/welcome-one.jpg
    - img/welcome-two.jpg
    - img/pilgrimage.png
    - img/waterfall.png
    - img/metal-crafts.png
    - img/mysterious-cg.png
    - img/cave.png
    - img/food.png
    - img/tirathgarh.png
    - img/chitrakoot.jpg
    - img/temple.png
    - img/tribal.png
    - img/logo.png


